
# Pipeline for pull requests

variables:
  dmd_version: 2.087.1

trigger: none

pr:
  branches:
    include:
    - '*' 


jobs:
- template: job_linux_cli_unittest.yml
- template: job_windows_cli_unittest.yml
- template: job_osx_cli_unittest.yml

- template: job_linux_gtk_unittest.yml
- template: job_windows_gtk_unittest.yml
- template: job_osx_gtk_unittest.yml

- template: job_linux_cli_release.yml
- template: job_windows_cli_release.yml
- template: job_osx_cli_release.yml

- template: job_linux_gtk_release.yml
- template: job_windows_gtk_release.yml
- template: job_osx_gtk_release.yml

- template: job_linux_appimage_create.yml



# - job: Linux_GTK_AppImage_Extract
#   pool:
#     name: Hosted Ubuntu 1604
#   steps:
#   - template: dub_install_linux.yml
#   - template: gtk_install_linux.yml
#   - script: dub build -c GTK -b release --arch=x86_64
#     displayName: GTK Release
#   - template: appimage_create.yml
#   - bash: chmod +x $(System.DefaultWorkingDirectory)/Drill-release-x86_64.AppImage
#     displayName: Set AppImage executable
#   - bash: $(System.DefaultWorkingDirectory)/Drill-release-x86_64.AppImage --appimage-extract
#     displayName: Extract AppImage

# - job: Linux_GTK_AppImage_Mount
#   pool:
#     name: Hosted Ubuntu 1604
#   steps:
#   - template: dub_install_linux.yml
#   - template: gtk_install_linux.yml
#   - script: dub build -c GTK -b release --arch=x86_64
#     displayName: GTK Release
#   - template: appimage_create.yml
#   - bash: chmod +x $(System.DefaultWorkingDirectory)/Drill-release-x86_64.AppImage
#     displayName: Set AppImage executable
#   - bash: $(System.DefaultWorkingDirectory)/Drill-release-x86_64.AppImage --appimage-mount &
#     displayName: Mount AppImage
#   - bash: sleep 3
#     displayName: sleep 3 seconds
