
language: bash

fast_finish: true

os:
  - windows
  - linux
  - osx

env:
  - DMD_VERSION=2.087.1 MAIN_VERSION=2


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then test -d /usr/local/opt/gtk+3/lib  || { rmdir /usr/local/opt/gtk+3; brew install gtk+3; }; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then test -d /usr/local/opt/glib/lib   || { rmdir /usr/local/opt/glib; brew install glib; }; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then test -d /usr/local/opt/gobject-introspection/lib  || { rmdir /usr/local/opt/gobject-introspection; brew install gobject-introspection; }; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then test -d /usr/local/opt/p7zip/lib  || { rmdir /usr/local/opt/p7zip; brew install p7zip; }; fi;

install:
  - if [ ! -d dmd."$DMD_VERSION" ]; then source .travis/install_d.bash; fi;
  - bash .travis/install_gtk.bash
  # Install 7zip
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y p7zip-full 1>/dev/null; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install p7zip; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then   sudo apt install -y appstream 1>/dev/null; fi;


script:
   # DO NOT USE "bash" here and inside sub-scripts, but use "source"
   # so we can change global variables like PATH in sub-scripts
   - set -e
   - source .travis/pipeline.bash

  #  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.travis/rolling_release.bash; fi
   
before_cache:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi;
  # - DIR="$PWD/dmd2"
  # - if [! -d "$DIR" ]; then source ./.travis/install_d.bash; fi;

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar/gtk+3
    - /usr/local/opt/gtk+3
    - /usr/local/Cellar/glib
    - /usr/local/opt/glib
    - /usr/local/Cellar/gobject-introspection
    - /usr/local/opt/gobject-introspection
    - /usr/local/Cellar/p7zip
    - /usr/local/opt/p7zip
    - dmd."$DMD_VERSION"
