# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Test
  jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
    - script: python .travis.py
  - job: Mac
    pool:
      vmImage: macos-10.13
    steps:
    - script: python .travis.py
  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: python .travis.py


