# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo snap install --classic --channel=edge ldc2
  displayName: 'Install ldc2 from the snap store'

- script: |
    sudo apt install desktop-file-utils
    sudo apt install p7zip-full
    sudo apt install dub
  displayName: 'Install other dependencies'

- script: |
    cd Source/Frontend/GTK
    dub build -b release --arch=x86_64 --compiler=ldc2
    cd ../../../
  displayName: 'Build CLI'
