filename = 'build/drill-0.0.1.dmg'
volume_label = 'drill-0.0.1'
format = 'UDZO'
filesystem = 'HFS+'
size = None
files = ['build/Drill.app']
symlinks = {'Applications': '/Applications'}
icon_locations = {'Applications': (500, 120), 'Drill.app': (140, 120)}
icon = '/Users/yatima/Documents/GitHub/Drill/src/assets/drill.icns'
background = 'builtin-arrow'
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
sidebar_width = None
window_rect = ((100, 100), (640, 380))
show_icon_preview = False
include_icon_view_settings = 'auto'
include_list_view_settings = 'auto'
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = 'bottom'
text_size = 16
icon_size = 128
icon_locations = {'Applications': (500, 120), 'Drill.app': (140, 120)}
list_sort_by = None
list_use_relative_dates = None
list_calculate_all_sizes = None
license = None
