version: "3.4"

services:

  drill-linux-cli:
    image: drill-linux-env
    build:
      context: ../
      dockerfile: Docker/Linux.Dockerfile
      args:
        - DMD_VERSION=2.098.0
    volumes:
      - ../:/Source
    working_dir: /Source
    command: >
      /bin/bash -c 'echo $DRILL_VERSION > DRILL_VERSION
      && dub clean
      && dub build -b release -c CLI --parallel --arch=x86_64
      && chmod +x /Source/Build/Drill-CLI-linux-x86_64-release/drill-search-cli
      && /Source/Build/Drill-CLI-linux-x86_64-release/drill-search-cli -ds drill'

  drill-linux-gtk:
    image: drill-linux-env
    build:
      context: ../
      dockerfile: Docker/Linux.Dockerfile
      args:
        - DMD_VERSION=2.098.0
    volumes:
      - ../:/Source
    working_dir: /Source
    command: >
      /bin/bash -c 'echo $DRILL_VERSION > DRILL_VERSION
      && dub clean
      && dub build -b release -c GTK --parallel --arch=x86_64'
  
  drill-windows-cli:
    image: drill-windows-env
    build:
      context: ../
      dockerfile: Docker/Windows.Dockerfile
    volumes:
      - ../:C:/Source
    working_dir: C:/Source
    command: >
      cmd /c 'echo $DRILL_VERSION > DRILL_VERSION
      && dub clean
      && dub build -b release -c CLI --parallel --arch=x86_64
      && Build\Drill-CLI-windows-x86_64-release\drill-search-cli.exe -ds drill'
