version: "3.4"

services:

  drill-cli:
    image: drill-env
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    volumes:
      - ../:/Source
    working_dir: /Source
    command: >
      /bin/bash -c 'echo $DRILL_VERSION > DRILL_VERSION
      && /dmd2/linux/bin64/dub clean
      && /dmd2/linux/bin64/dub build -b release -c CLI --parallel --arch=x86_64
      && chmod +x build/Drill-CLI-linux-x86_64-release/drill-search-cli
      && ./build/Drill-CLI-linux-x86_64-release/drill-search-cli -ds drill'

  drill-gtk:
    image: drill-env
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    volumes:
      - ../:/Source
    working_dir: /Source
    command: >
      /bin/bash -c 'echo $DRILL_VERSION > DRILL_VERSION
      && /dmd2/linux/bin64/dub clean
      && /dmd2/linux/bin64/dub build -b release -c GTK --parallel --arch=x86_64'
