CXX = undefined
CXXFLAGS = undefined
LDFLAGS = undefined

SRC = 
OBJ = $(SRC:.cc=.o)
EXEC = libDrillCore.a

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $(OBJ) $(LBLIBS)

clean:
	rm -rf $(OBJ) $(EXEC)