steps:
- script: wget -c http://downloads.dlang.org/releases/2.x/$(dmd_version)/dmd.$(dmd_version).linux.tar.xz -O $(System.DefaultWorkingDirectory)/dmd.$(dmd_version).linux.tar.xz 
  displayName: 'Download dmd & dub'
- script: 7z x -aos dmd.$(dmd_version).linux.tar.xz
- script: 7z x -aos dmd.$(dmd_version).linux.tar
- script: echo "##vso[task.setvariable variable=DUB_LOCATION;]$(System.DefaultWorkingDirectory)/dmd2/linux/bin64"
- script: chmod +x $(DUB_LOCATION)/dmd
- script: chmod +x $(DUB_LOCATION)/dub
- script: echo "##vso[task.setvariable variable=PATH;]$(System.DefaultWorkingDirectory)/dmd2/linux/bin64:$PATH"
