jobs:
- job: OSX_GTK_Unittest
  pool:
    name: Hosted macOS
  steps:
  - template: dub_install_osx.yml
  - template: gtk_install_osx.yml
  - script: dub test -c GTK --arch=x86_64
    displayName: GTK Unittest
