jobs:
- job: Linux_GTK_Release
  dependsOn: 
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - template: dub_install_linux.yml
  - template: gtk_install_linux.yml
  - script: echo -n $(Build.BuildNumber) > AZURE_VERSION
  - script: dub build -c GTK -b release-azure --arch=x86_64
    displayName: GTK Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-linux-x86_64.zip $PWD/Build/Drill-GTK-linux-x86_64-release/*
  - template: upload_file.yml
    parameters:
      name: Drill-$(Build.BuildNumber)-linux-x86_64.zip
      package: Portable-Beta
