jobs:
- job: Windows_GTK_Unittest
  pool:
    name: Hosted VS2017
  steps:
  - template: dub_install_windows.yml
  - template: gtk_install_windows.yml
  - script: dub test -c GTK --arch=x86_64
    displayName: GTK Unittest
