jobs:
- job: OSX_GTK_Release
  pool:
    name: Hosted macOS
  steps:
  - template: dub_install_osx.yml
  - template: gtk_install_osx.yml
  - script: dub build -c GTK -b release --arch=x86_64
    displayName: GTK Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-osx-x86_64.zip $PWD/Build/Drill-GTK-osx-x86_64-release/*
  # - script: curl -T Drill-GTK-osx-x86_64-release.zip -uyatima1460:$(BINTRAY_API_KEY) https://api.bintray.com/content/yatima1460/Drill/Portable/$(Build.BuildNumber)/Drill-GTK-osx-x86_64-release-$(Build.BuildNumber).zip
  # - script: curl -X POST -uyatima1460:$(BINTRAY_API_KEY) https://api.bintray.com/content/yatima1460/Drill/Portable/$(Build.BuildNumber)/publish
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: Drill-$(Build.BuildNumber)-osx-x86_64.zip
      artifact: Drill-$(Build.BuildNumber)-osx-x86_64.zip
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'githubtoken'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: $(Build.BuildNumber)
      title: $(Build.BuildNumber)
      releaseNotesSource: 'input'
      releaseNotes: $(Build.BuildNumber)
      isPreRelease: true
      assetUploadMode: replace
      addChangeLog: false
      assets: Drill-$(Build.BuildNumber)-osx-x86_64.zip