jobs:
- job: Linux_GTK_Release
  dependsOn: 
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - template: dub_install_linux.yml
  - template: gtk_install_linux.yml
  - script: dub build -c GTK -b release --arch=x86_64
    displayName: GTK Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-linux-x86_64.zip $PWD/Build/Drill-GTK-linux-x86_64-release/*

  # - script: curl -T Drill-GTK-linux-x86_64-release.zip -uyatima1460:$(BINTRAY_API_KEY) https://api.bintray.com/content/yatima1460/Drill/Portable-Beta/$(Build.BuildNumber)/Drill-GTK-linux-x86_64-release-$(Build.BuildNumber).zip
  # - script: curl -X POST -uyatima1460:$(BINTRAY_API_KEY) https://api.bintray.com/content/yatima1460/Drill/Portable-Beta/$(Build.BuildNumber)/publish
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: Drill-$(Build.BuildNumber)-linux-x86_64.zip
      artifact: Drill-$(Build.BuildNumber)-linux-x86_64.zip
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'githubtoken'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: $(Build.BuildNumber)-Beta
      title: $(Build.BuildNumber)-Beta
      releaseNotesSource: 'input'
      releaseNotes: $(Build.BuildNumber)-Beta
      isPreRelease: true
      assetUploadMode: replace
      addChangeLog: false
      assets: Drill-$(Build.BuildNumber)-linux-x86_64.zip

