jobs:
- job: Windows_GTK_Release
  pool:
    name: Hosted VS2017
  steps:
  - template: dub_install_windows.yml
  - template: gtk_install_windows.yml
  - powershell: $(Build.BuildNumber) | Out-File -encoding ascii AZURE_VERSION -NoNewline
  - script: dub build -c GTK -b release-azure --arch=x86_64
    displayName: GTK Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-windows-x86_64.zip $PWD/Build/Drill-GTK-windows-x86_64-release/*
  - template: upload_file.yml
    parameters:
      name: Drill-$(Build.BuildNumber)-windows-x86_64.zip
      package: Portable-Beta