jobs:
- job: Windows_CLI_Release
  pool:
    name: Hosted VS2017
  steps:
  - template: dub_install_windows.yml
  - powershell: $(Build.BuildNumber) | Out-File -encoding ascii AZURE_VERSION -NoNewline
  - script: dub run -c CLI -b release-azure --arch=x86_64
    displayName: CLI Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-CLI-windows-x86_64.zip $PWD/Build/Drill-CLI-windows-x86_64-release/*
  - template: upload_file.yml
    parameters:
      name: Drill-$(Build.BuildNumber)-CLI-windows-x86_64.zip
      package: Portable-Beta
