jobs:
- job: OSX_CLI_Release
  pool:
    name: Hosted macOS
  steps:
  - template: dub_install_osx.yml
  - script: echo -n $(Build.BuildNumber) > AZURE_VERSION
  - script: dub build -c CLI -b release-azure --arch=x86_64
    displayName: CLI Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-CLI-osx-x86_64.zip $PWD/Build/Drill-CLI-osx-x86_64-release/*
  - template: upload_file.yml
    parameters:
      name: Drill-$(Build.BuildNumber)-CLI-osx-x86_64.zip
      package: Portable-Beta


