jobs:
- job: Windows_GTK_Unittest
  pool:
    name: Hosted VS2017
  steps:
  - template: dub_install_windows.yml
  - template: gtk_install_windows.yml
  - script: dub run -c GTK -b unittest --arch=x86_64 -- unittest
    displayName: GTK Unittest