jobs:
- job: Linux_GTK_Unittest
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - template: dub_install_linux.yml
  - template: gtk_install_linux.yml
  - script: dub test -c GTK --arch=x86_64
    displayName: GTK Unittest
