jobs:
- job: Linux_CLI_Release
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - template: dub_install_linux.yml
  - script: dub run -c CLI -b release --arch=x86_64
    displayName: CLI Release
  - bash: 7z a -tzip Drill-$(Build.BuildNumber)-CLI-linux-x86_64.zip $PWD/Build/Drill-CLI-linux-x86_64-release/*

  # - script: curl -T Drill-$(Build.BuildNumber)-CLI-linux-x86_64.zip -uyatima1460:$(BINTRAY_API_KEY) https://api.bintray.com/content/yatima1460/Drill/Portable-Beta/$(Build.BuildNumber)/Drill-CLI-linux-x86_64-release-$(Build.BuildNumber).zip
  # - script: curl -X POST -uyatima1460:$(BINTRAY_API_KEY) https://api.bintray.com/content/yatima1460/Drill/Portable-Beta/$(Build.BuildNumber)/publish
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: Drill-$(Build.BuildNumber)-CLI-linux-x86_64.zip
      artifact: Drill-$(Build.BuildNumber)-CLI-linux-x86_64.zip