name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: .

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build win-x64
      run: dotnet publish WinForms\WinForms.csproj /p:Configuration=Release /p:Platform=x64 /p:SelfContained=true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:TargetFramework=net8.0-windows /p:RuntimeIdentifier=win-x64 /p:PublishDir=Drill_win-x64

    - name: Zip win-x64
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Drill_win-x64.zip WinForms/Drill_win-x64

    - name: Upload win-x64
      uses: actions/upload-artifact@v4
      with:
        name: Drill_win-x64
        path: Drill_win-x64.zip
        if-no-files-found: error

    - name: Create a Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: Drill_win-x64.zip


    #- name: Build MAUI
    #  run: dotnet publish --maxCpuCount -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None .\Drill\Drill.csproj


    #- name: Upload Win
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: Drill_win10-x64
    #    path: Drill\bin\Release\net8.0-windows10.0.19041.0\win10-x64\publish
    #    if-no-files-found: error

    #- name: Build Mac
    #  run: dotnet publish --maxCpuCount -f net8.0-maccatalyst -c Release -p:RuntimeIdentifierOverride=maccatalyst-arm64 -p:WindowsPackageType=None .\Drill\Drill.csproj
  
    #- name: Upload Mac
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: Drill_win10-x64
    #    path: Drill\bin\Release\net8.0-maccatalyst\maccatalyst-arm64\publish
    #    if-no-files-found: error
