name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: dotnet build -t:Build -p:Configuration=Release -f net8.0-windows10.0.19041.0 UI\UI.csproj /p:WindowsAppSDKSelfContained=true /p:Platform=x64 /p:WindowsPackageType=None 

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Drill_win10-x64
        path: UI/bin/Release/net8.0-windows10.0.19041.0/win10-x64
        if-no-files-found: error
