name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: .

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build Win
      run: dotnet publish --maxCpuCount -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None .\Drill\Drill.csproj

    - name: Upload Win
      uses: actions/upload-artifact@v4
      with:
        name: Drill_win10-x64
        path: Drill\bin\Release\net8.0-windows10.0.19041.0\win10-x64\publish
        if-no-files-found: error

    - name: Build Mac
      run: dotnet publish --maxCpuCount -f net8.0-maccatalyst -c Release -p:RuntimeIdentifierOverride=maccatalyst-arm64 -p:WindowsPackageType=None .\Drill\Drill.csproj
  
    - name: Upload Mac
      uses: actions/upload-artifact@v4
      with:
        name: Drill_win10-x64
        path: Drill\bin\Release\net8.0-maccatalyst\maccatalyst-arm64\publish
        if-no-files-found: error