name: CD

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read

env:
  QT_QPA_PLATFORM: offscreen

jobs:

  

  # tests:
  #   runs-on: ubuntu-latest
  #   env:
  #       DISPLAY: ':99.0'
  #   steps:
  #       - uses: actions/checkout@v4.2.2
  #       - name: Set up Python 3.12
  #         uses: actions/setup-python@v5.6.0
  #         with:
  #           python-version: "3.12"
  #       - name: Install Python dependencies
  #         run:  |
  #           python -m pip install --upgrade pip
  #           pip install -r requirements.txt
  #           pip install flake8 pytest pytest-qt
  #       - name: Lint tests with flake8
  #         run: flake8 ./tests --count --show-source --statistics
  #       - name: Run tests
  #         run: pytest tests/

  # linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4.2.2
  #     - name: Set up Python 3.12
  #       uses: actions/setup-python@v5.6.0
  #       with:
  #         python-version: "3.12"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install cx_Freeze 
  #     - name: Run cx_freeze
  #       run: python setup.py bdist_appimage
  #     - name: Upload cx_freeze appimage
  #       uses: actions/upload-artifact@v4.6.2
  #       with:
  #         name: Drill-linux.appimage
  #         path: build/*.appimage
  #         if-no-files-found: error

  # macos:

  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v4.2.2
  #   - name: Set up Python 3.12
  #     uses: actions/setup-python@v5.6.0
  #     with:
  #       python-version: "3.12"
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install cx_Freeze dmgbuild
  #   - name: Run cx_freeze dmg
  #     run: python setup.py bdist_dmg
  #   - name: Upload cx_freeze app
  #     uses: actions/upload-artifact@v4.6.2
  #     with:
  #       name: Drill-macos.app
  #       path: build/dist/*.app
  #       if-no-files-found: error
  #   - name: Upload cx_freeze dmg
  #     uses: actions/upload-artifact@v4.6.2
  #     with:
  #       name: Drill-macos.dmg
  #       path: build/*.dmg
  #       if-no-files-found: error
        

  windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.12" # msi not available for 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-cd.txt
    - name: Lint tests with flake8
      run: python -m flake8 ./src --count --show-source --statistics
    - name: Run tests
      run: python -m pytest tests/
    - name: Run cx_freeze
      run: python setup.py build_exe
    - name: Upload exe
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Drill-windows.zip
        path: build/exe.win-amd64-3.12

    # - name: Upload msi
    #   uses: actions/upload-artifact@v4.6.2
    #   with:
    #     name: Drill-windows.msi
    #     path: build/*.msi
    #     if-no-files-found: error
