name: ci-core

on:

  pull_request:

    paths:
      - core/**
      - .github/workflows/ci-core.yml


jobs:

  ci-core:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Run CMake
      run: mkdir build && cd build && cmake ..
      working-directory: core
    - name: Build
      run: make -j`nproc`
      working-directory: core/build
