name: ci

on:

  pull_request:
    branches:
      - master
      - main
      - cpp17
    paths-ignore:
      - '**/*.md'

jobs:

  linux:

    name: "Linux"
    runs-on: ubuntu-22.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        path: Drill
    - name: Run CMake
      run: mkdir build && cmake ..
      working-directory: Drill
    - name: Build
      run: make -j`nproc`
      working-directory: Drill/build
