name: macOS Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'src/assets/**'
      - 'scripts/build_mac.sh'
      - '.github/workflows/**'
      - 'requirements-cd.txt'
      - 'setup.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'src/assets/**'
      - 'scripts/build_mac.sh'
      - '.github/workflows/**'
      - 'requirements-cd.txt'
      - 'setup.py'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    name: Build macOS app+dmg
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"

      - name: Build app and dmg
        run: ./scripts/build_mac.sh

      - name: Upload macOS app
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Drill-macos-app
          path: |
            build/*.app
            build/dist/*.app
          if-no-files-found: error
          retention-days: 7
          compression-level: 9

      - name: Upload macOS dmg
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Drill-macos-dmg
          path: build/*.dmg
          if-no-files-found: error
          retention-days: 7
          compression-level: 9
